name: login_flutter_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^3.0.1
  google_fonts: ^6.1.0

  
  get: ^4.6.6

  
  liquid_swipe: ^3.0.0
  smooth_page_indicator: ^1.0.0+2

  
  flutter_otp_text_field: ^1.1.1


  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.3
  flutter_facebook_auth: ^6.0.3
  google_sign_in: ^6.1.6



  cupertino_icons: ^1.0.8
  line_awesome_flutter: ^2.0.0
  flutter_native_splash: ^2.3.6
  bloc: ^8.1.4
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  qr_code_scanner: ^1.0.1
  google_maps_flutter: ^2.6.1
  location: ^6.0.1
  flutter_bloc: ^8.1.5
  flutter_polyline_points: ^2.0.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.7
  retrofit_generator: ^8.1.0



flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/images/
    - assets/images/profile/profile-pic.png
    - assets/images/profile/logo.png
    - assets/images/dashboard/
    - assets/images/dashboard/dash-04.png
    - assets/images/dashboard/dash-01.png
    - assets/images/dashboard/dash-02.png
    - assets/images/dashboard/dash-03.png
    - assets/images/splash_images/splash-screen-image.png
    - assets/images/welcome_images/welcome-screen-image.png
    - assets/images/forget_password/
    - assets/images/on_boarding_images/on-boarding-image-1.png
    - assets/images/on_boarding_images/on-boarding-image-2.png
    - assets/images/on_boarding_images/on-boarding-image-3.png

